export const BD_REGIONS = [
  {
    division: 'Dhaka',
    districts: [
      {
        name: 'Dhaka',
        upazilas: [
          'Adabor',
          'Badda',
          'Bangshal',
          'Biman Bandar',
          'Cantonment',
          'Chak Bazar',
          'Dakshinkhan',
          'Darus Salam',
          'Demra',
          'Dhanmondi',
          'Dhamrai',
          'Dohar',
          'Gendaria',
          'Gulshan',
          'Hazaribagh',
          'Jatrabari',
          'Kadamtali',
          'Kafrul',
          'Kalabagan',
          'Kamrangirchar',
          'Keraniganj',
          'Khilgaon',
          'Khilkhet',
          'Kotwali',
          'Lalbagh',
          'Mirpur',
          'Mohammadpur',
          'Motijheel',
          'Mugda',
          'Nawabganj',
          'New Market',
          'Pallabi',
          'Paltan',
          'Ramna',
          'Rampura',
          'Sabujbagh',
          'Savar',
          'Shah Ali',
          'Shahbagh',
          'Sher-e-Bangla Nagar',
          'Shyampur',
          'Sutrapur',
          'Tejgaon',
          'Tejgaon Industrial Area',
          'Turag',
          'Uttara',
          'Uttar Khan',
          'Vatara',
          'Wari',
        ],
      },
      {
        name: 'Faridpur',
        upazilas: [
          'Alfadanga',
          'Bhanga',
          'Boalmari',
          'Charbhadrasan',
          'Faridpur Sadar',
          'Madhukhali',
          'Nagarkanda',
          'Sadarpur',
          'Saltha',
        ],
      },
      {
        name: 'Gazipur',
        upazilas: [
          'Gazipur Sadar',
          'Kaliakair',
          'Kaliganj',
          'Kapasia',
          'Sreepur',
          'Tongi',
        ],
      },
      {
        name: 'Gopalganj',
        upazilas: [
          'Gopalganj Sadar',
          'Kashiani',
          'Kotalipara',
          'Muksudpur',
          'Tungipara',
        ],
      },
      {
        name: 'Kishoreganj',
        upazilas: [
          'Austagram',
          'Bajitpur',
          'Bhairab',
          'Hossainpur',
          'Itna',
          'Karimganj',
          'Katiadi',
          'Kishoreganj Sadar',
          'Kuliarchar',
          'Mithamain',
          'Nikli',
          'Pakundia',
          'Tarail',
        ],
      },
      {
        name: 'Madaripur',
        upazilas: [
          'Dasar',
          'Kalkini',
          'Madaripur Sadar',
          'Rajoir',
          'Shibchar',
        ],
      },
      {
        name: 'Manikganj',
        upazilas: [
          'Daulatpur',
          'Ghior',
          'Harirampur',
          'Manikganj Sadar',
          'Saturia',
          'Shibalaya',
          'Singair',
        ],
      },
      {
        name: 'Munshiganj',
        upazilas: [
          'Gazaria',
          'Lohajang',
          'Munshiganj Sadar',
          'Sirajdikhan',
          'Sreenagar',
          'Tongibari',
        ],
      },
      {
        name: 'Narayanganj',
        upazilas: [
          'Araihazar',
          'Bandar',
          'Narayanganj Sadar',
          'Rupganj',
          'Sonargaon',
        ],
      },
      {
        name: 'Narsingdi',
        upazilas: [
          'Belabo',
          'Monohardi',
          'Narsingdi Sadar',
          'Palash',
          'Raipura',
          'Shibpur',
        ],
      },
      {
        name: 'Rajbari',
        upazilas: [
          'Baliakandi',
          'Goalanda',
          'Kalukhali',
          'Pangsha',
          'Rajbari Sadar',
        ],
      },
      {
        name: 'Shariatpur',
        upazilas: [
          'Bhedarganj',
          'Damudya',
          'Gosairhat',
          'Jajira',
          'Naria',
          'Shariatpur Sadar',
        ],
      },
      {
        name: 'Tangail',
        upazilas: [
          'Basail',
          'Bhuapur',
          'Delduar',
          'Dhanbari',
          'Ghatail',
          'Gopalpur',
          'Kalihati',
          'Madhupur',
          'Mirzapur',
          'Nagarpur',
          'Sakhipur',
          'Tangail Sadar',
        ],
      },
    ],
  },

  {
    division: 'Chattogram',
    districts: [
      {
        name: 'Bandarban',
        upazilas: [
          'Alikadam',
          'Bandarban Sadar',
          'Lama',
          'Naikhongchhari',
          'Rowangchhari',
          'Ruma',
          'Thanchi',
        ],
      },
      {
        name: 'Brahmanbaria',
        upazilas: [
          'Akhaura',
          'Ashuganj',
          'Bancharampur',
          'Brahmanbaria Sadar',
          'Bijoynagar',
          'Kasba',
          'Nabinagar',
          'Nasirnagar',
          'Sarail',
        ],
      },
      {
        name: 'Chandpur',
        upazilas: [
          'Chandpur Sadar',
          'Faridganj',
          'Haimchar',
          'Hajiganj',
          'Kachua',
          'Matlab Dakshin',
          'Matlab Uttar',
          'Shahrasti',
        ],
      },
      {
        name: 'Chattogram',
        upazilas: [
          'Anwara',
          'Banshkhali',
          'Boalkhali',
          'Chandanaish',
          'Fatikchhari',
          'Hathazari',
          'Karnaphuli',
          'Lohagara',
          'Mirsharai',
          'Patiya',
          'Rangunia',
          'Raozan',
          'Sandwip',
          'Satkania',
          'Sitakunda',
        ],
      },
      {
        name: "Cox's Bazar",
        upazilas: [
          'Chakaria',
          "Cox's Bazar Sadar",
          'Eidgaon',
          'Kutubdia',
          'Maheshkhali',
          'Pekua',
          'Ramu',
          'Teknaf',
          'Ukhiya',
        ],
      },
      {
        name: 'Cumilla',
        upazilas: [
          'Barura',
          'Brahmanpara',
          'Burichang',
          'Chandina',
          'Chauddagram',
          'Cumilla Adarsha Sadar',
          'Cumilla Sadar Dakshin',
          'Daudkandi',
          'Debidwar',
          'Homna',
          'Laksam',
          'Lalmai',
          'Meghna',
          'Monoharganj',
          'Muradnagar',
          'Nangalkot',
          'Titas',
        ],
      },
      {
        name: 'Feni',
        upazilas: [
          'Chhagalnaiya',
          'Daganbhuiyan',
          'Feni Sadar',
          'Fulgazi',
          'Parshuram',
          'Sonagazi',
        ],
      },
      {
        name: 'Khagrachhari',
        upazilas: [
          'Dighinala',
          'Guimara',
          'Khagrachhari Sadar',
          'Lakshmichhari',
          'Mahalchhari',
          'Manikchhari',
          'Matiranga',
          'Panchhari',
          'Ramgarh',
        ],
      },
      {
        name: 'Lakshmipur',
        upazilas: [
          'Kamalnagar',
          'Lakshmipur Sadar',
          'Raipur',
          'Ramganj',
          'Ramgati',
        ],
      },
      {
        name: 'Noakhali',
        upazilas: [
          'Begumganj',
          'Chatkhil',
          'Companiganj',
          'Hatiya',
          'Kabirhat',
          'Noakhali Sadar',
          'Senbagh',
          'Sonaimuri',
          'Subarnachar',
        ],
      },
      {
        name: 'Rangamati',
        upazilas: [
          'Baghaichhari',
          'Barkal',
          'Belaichhari',
          'Juraichhari',
          'Kaptai',
          'Kawkhali',
          'Langadu',
          'Naniarchar',
          'Rajasthali',
          'Rangamati Sadar',
        ],
      },
    ],
  },

  {
    division: 'Rajshahi',
    districts: [
      {
        name: 'Bogura',
        upazilas: [
          'Adamdighi',
          'Bogura Sadar',
          'Dhunat',
          'Dhupchanchia',
          'Gabtali',
          'Kahaloo',
          'Nandigram',
          'Sariakandi',
          'Shajahanpur',
          'Sherpur',
          'Shibganj',
          'Sonatala',
        ],
      },
      {
        name: 'Chapainawabganj',
        upazilas: [
          'Bholahat',
          'Gomastapur',
          'Nachole',
          'Chapainawabganj Sadar',
          'Shibganj',
        ],
      },
      {
        name: 'Joypurhat',
        upazilas: [
          'Akkelpur',
          'Joypurhat Sadar',
          'Kalai',
          'Khetlal',
          'Panchbibi',
        ],
      },
      {
        name: 'Naogaon',
        upazilas: [
          'Atrai',
          'Badalgachhi',
          'Dhamoirhat',
          'Manda',
          'Mahadebpur',
          'Naogaon Sadar',
          'Niamatpur',
          'Patnitala',
          'Porsha',
          'Raninagar',
          'Sapahar',
        ],
      },
      {
        name: 'Natore',
        upazilas: [
          'Bagatipara',
          'Baraigram',
          'Gurudaspur',
          'Lalpur',
          'Naldanga',
          'Natore Sadar',
          'Singra',
        ],
      },
      {
        name: 'Pabna',
        upazilas: [
          'Atgharia',
          'Bera',
          'Bhangura',
          'Chatmohar',
          'Faridpur',
          'Ishwardi',
          'Pabna Sadar',
          'Santhia',
          'Sujanagar',
        ],
      },
      {
        name: 'Rajshahi',
        upazilas: [
          'Bagha',
          'Bagmara',
          'Charghat',
          'Durgapur',
          'Godagari',
          'Mohanpur',
          'Paba',
          'Puthia',
          'Tanore',
        ],
      },
      {
        name: 'Sirajganj',
        upazilas: [
          'Belkuchi',
          'Chauhali',
          'Kamarkhanda',
          'Kazipur',
          'Raiganj',
          'Shahjadpur',
          'Sirajganj Sadar',
          'Tarash',
          'Ullapara',
        ],
      },
    ],
  },

  {
    division: 'Khulna',
    districts: [
      {
        name: 'Bagerhat',
        upazilas: [
          'Bagerhat Sadar',
          'Chitalmari',
          'Fakirhat',
          'Kachua',
          'Mollahat',
          'Mongla',
          'Morrelganj',
          'Rampal',
          'Sarankhola',
        ],
      },
      {
        name: 'Chuadanga',
        upazilas: [
          'Alamdanga',
          'Chuadanga Sadar',
          'Damurhuda',
          'Jibannagar',
        ],
      },
      {
        name: 'Jashore',
        upazilas: [
          'Abhaynagar',
          'Bagherpara',
          'Chaugachha',
          'Jashore Sadar',
          'Jhikargachha',
          'Keshabpur',
          'Manirampur',
          'Sharsha',
        ],
      },
      {
        name: 'Jhenaidah',
        upazilas: [
          'Harinakunda',
          'Jhenaidah Sadar',
          'Kaliganj',
          'Kotchandpur',
          'Maheshpur',
          'Shailkupa',
        ],
      },
      {
        name: 'Khulna',
        upazilas: [
          'Batiaghata',
          'Dacope',
          'Dighalia',
          'Dumuria',
          'Koyra',
          'Paikgachha',
          'Phultala',
          'Rupsha',
          'Terokhada',
        ],
      },
      {
        name: 'Kushtia',
        upazilas: [
          'Bheramara',
          'Daulatpur',
          'Khoksa',
          'Kumarkhali',
          'Kushtia Sadar',
          'Mirpur',
        ],
      },
      {
        name: 'Magura',
        upazilas: [
          'Magura Sadar',
          'Mohammadpur',
          'Shalikha',
          'Sreepur',
        ],
      },
      {
        name: 'Meherpur',
        upazilas: [
          'Gangni',
          'Meherpur Sadar',
          'Mujibnagar',
        ],
      },
      {
        name: 'Narail',
        upazilas: [
          'Kalia',
          'Lohagara',
          'Narail Sadar',
        ],
      },
      {
        name: 'Satkhira',
        upazilas: [
          'Assasuni',
          'Debhata',
          'Kalaroa',
          'Kaliganj',
          'Satkhira Sadar',
          'Shyamnagar',
          'Tala',
        ],
      },
    ],
  },

  {
    division: 'Barishal',
    districts: [
      {
        name: 'Barguna',
        upazilas: [
          'Amtali',
          'Bamna',
          'Barguna Sadar',
          'Betagi',
          'Patharghata',
          'Taltali',
        ],
      },
      {
        name: 'Barishal',
        upazilas: [
          'Agailjhara',
          'Babuganj',
          'Bakerganj',
          'Banaripara',
          'Barishal Sadar',
          'Gournadi',
          'Hizla',
          'Mehendiganj',
          'Muladi',
          'Wazirpur',
        ],
      },
      {
        name: 'Bhola',
        upazilas: [
          'Bhola Sadar',
          'Borhanuddin',
          'Char Fasson',
          'Daulatkhan',
          'Lalmohan',
          'Manpura',
          'Tazumuddin',
        ],
      },
      {
        name: 'Jhalokathi',
        upazilas: [
          'Jhalokathi Sadar',
          'Kathalia',
          'Nalchity',
          'Rajapur',
        ],
      },
      {
        name: 'Patuakhali',
        upazilas: [
          'Bauphal',
          'Dashmina',
          'Dumki',
          'Galachipa',
          'Kalapara',
          'Mirzaganj',
          'Patuakhali Sadar',
          'Rangabali',
        ],
      },
      {
        name: 'Pirojpur',
        upazilas: [
          'Bhandaria',
          'Indurkani',
          'Kawkhali',
          'Mathbaria',
          'Nazirpur',
          'Nesarabad',
          'Pirojpur Sadar',
        ],
      },
    ],
  },

  {
    division: 'Sylhet',
    districts: [
      {
        name: 'Habiganj',
        upazilas: [
          'Ajmiriganj',
          'Bahubal',
          'Baniachong',
          'Chunarughat',
          'Habiganj Sadar',
          'Lakhai',
          'Madhabpur',
          'Nabiganj',
          'Shayestaganj',
        ],
      },
      {
        name: 'Moulvibazar',
        upazilas: [
          'Barlekha',
          'Juri',
          'Kamalganj',
          'Kulaura',
          'Moulvibazar Sadar',
          'Rajnagar',
          'Sreemangal',
        ],
      },
      {
        name: 'Sunamganj',
        upazilas: [
          'Bishwamvarpur',
          'Chhatak',
          'Derai',
          'Dharmapasha',
          'Doarabazar',
          'Jagannathpur',
          'Jamalganj',
          'Madhyanagar',
          'Shalla',
          'Shantiganj',
          'Sunamganj Sadar',
          'Tahirpur',
        ],
      },
      {
        name: 'Sylhet',
        upazilas: [
          'Balaganj',
          'Beanibazar',
          'Bishwanath',
          'Companiganj',
          'Dakshin Surma',
          'Fenchuganj',
          'Golapganj',
          'Gowainghat',
          'Jaintiapur',
          'Kanaighat',
          'Osmani Nagar',
          'Sylhet Sadar',
          'Zakiganj',
        ],
      },
    ],
  },

  {
    division: 'Rangpur',
    districts: [
      {
        name: 'Dinajpur',
        upazilas: [
          'Birampur',
          'Birganj',
          'Birol',
          'Bochaganj',
          'Chirirbandar',
          'Dinajpur Sadar',
          'Fulbari',
          'Ghoraghat',
          'Hakimpur',
          'Kaharole',
          'Khansama',
          'Nawabganj',
          'Parbatipur',
        ],
      },
      {
        name: 'Gaibandha',
        upazilas: [
          'Fulchhari',
          'Gaibandha Sadar',
          'Gobindaganj',
          'Palashbari',
          'Sadullapur',
          'Saghata',
          'Sundarganj',
        ],
      },
      {
        name: 'Kurigram',
        upazilas: [
          'Bhurungamari',
          'Char Rajibpur',
          'Chilmari',
          'Fulbari',
          'Kurigram Sadar',
          'Nageshwari',
          'Rajarhat',
          'Raomari',
          'Ulipur',
        ],
      },
      {
        name: 'Lalmonirhat',
        upazilas: [
          'Aditmari',
          'Hatibandha',
          'Kaliganj',
          'Lalmonirhat Sadar',
          'Patgram',
        ],
      },
      {
        name: 'Nilphamari',
        upazilas: [
          'Dimla',
          'Domar',
          'Jaldhaka',
          'Kishoreganj',
          'Nilphamari Sadar',
          'Saidpur',
        ],
      },
      {
        name: 'Panchagarh',
        upazilas: [
          'Atwari',
          'Boda',
          'Debiganj',
          'Panchagarh Sadar',
          'Tetulia',
        ],
      },
      {
        name: 'Rangpur',
        upazilas: [
          'Badarganj',
          'Gangachara',
          'Kaunia',
          'Mithapukur',
          'Pirgachha',
          'Pirganj',
          'Rangpur Sadar',
          'Taraganj',
        ],
      },
      {
        name: 'Thakurgaon',
        upazilas: [
          'Baliadangi',
          'Haripur',
          'Pirganj',
          'Ranisankail',
          'Thakurgaon Sadar',
        ],
      },
    ],
  },

  {
    division: 'Mymensingh',
    districts: [
      {
        name: 'Jamalpur',
        upazilas: [
          'Bakshiganj',
          'Dewanganj',
          'Islampur',
          'Jamalpur Sadar',
          'Madarganj',
          'Melandaha',
          'Sarishabari',
        ],
      },
      {
        name: 'Mymensingh',
        upazilas: [
          'Bhaluka',
          'Dhobaura',
          'Fulbaria',
          'Gaffargaon',
          'Gauripur',
          'Haluaghat',
          'Ishwarganj',
          'Muktagachha',
          'Mymensingh Sadar',
          'Nandail',
          'Phulpur',
          'Tarakanda',
          'Trishal',
        ],
      },
      {
        name: 'Netrokona',
        upazilas: [
          'Atpara',
          'Barhatta',
          'Durgapur',
          'Kalmakanda',
          'Kendua',
          'Khaliajuri',
          'Madan',
          'Mohanganj',
          'Netrokona Sadar',
          'Purbadhala',
        ],
      },
      {
        name: 'Sherpur',
        upazilas: [
          'Jhenaigati',
          'Nakla',
          'Nalitabari',
          'Sherpur Sadar',
          'Sreebardi',
        ],
      },
    ],
  },
];

export const BD_DISTRICTS = BD_REGIONS.flatMap((region) => region.districts);